version: '3'

services:

  server:
    container_name: chatgpt-wework
    image: ibfpig/openai-wework:1.1.0
    ports:
      - "3200:3200"
    volumes:
      - ./work/data:/app/data
    environment:
        api_key: ${wework_token}
        app_port: :3200
        app_model: text-davinci-003
        wework_token: ${wework_token}
        wework_encodingAeskey: ${wework_encodingAeskey}
        wework_corpid: ${wework_corpid}
        wework_secret: ${wework_secret}
        wework_agentid: ${api_type}
        api_type: ${api_type}
        chatgpt_cookie: ${chatgpt_cookie}
        chatgpt_authorization: ${chatgpt_authorization}
        chatgpt_useragent: ${chatgpt_useragent}
    restart: always
